function row(label, value, note, tone = "") {
  return { label, value, note, tone };
}

function board(outer, inner, order, tx) {
  return [outer, inner, order, tx];
}

const base = {
  group: "3. 메서드를 어떻게 묶을까",
  tone: "work",
};

export const propagationScenarios = [
  {
    ...base,
    id: "prop-required",
    title: "주문과 결제는 같이 간다",
    blurb: "결제가 실패하면 주문도 없어야 할 때. 옵션 이름은 REQUIRED, 아무 표시도 안 하면 이것입니다.",
    tag: "REQUIRED",
    steps: [
      {
        name: "주문 서비스",
        sub: "Tx 시작",
        layer: "spring",
        shape: "box",
        title: "주문이 먼저 트랜잭션을 연다",
        plain: "주문과 결제는 한 묶음입니다. 결제가 실패하면 재고 감소도 같이 취소됩니다.",
        body: "손님이 책을 주문합니다. OrderService.placeOrder는 @Transactional이고, 전파를 생략하면 REQUIRED입니다. 진행 중인 트랜잭션이 없으니 새 트랜잭션을 엽니다.",
        code: "@Transactional // propagation = REQUIRED\npublic Order placeOrder(Long bookId, int qty) {\n  bookRepository.decreaseStock(bookId, qty);\n  paymentService.charge(bookId, qty);\n  return orderRepository.save(new Order(bookId, qty));\n}",
        stats: board(
          row("바깥 트랜잭션", "열림", "OrderService", "hot"),
          row("결제 트랜잭션", "아직", "참여 전"),
          row("확정 재고", "10", "커밋 전"),
          row("커넥션", "1개", "풀에서 대여")
        ),
        acid: ["A"],
        tone: "work",
        callout: "이럴 때 고릅니다. 재고, 결제, 주문이 전부 성공하거나 전부 취소되어야 할 때입니다.",
      },
      {
        name: "재고 차감",
        sub: "같은 Tx",
        layer: "db",
        shape: "cylinder",
        title: "재고는 이 트랜잭션 안에서만 9이다",
        body: "UPDATE는 실행됐지만 커밋 전입니다. 확정 재고는 10, 이 트랜잭션이 보는 재고는 9입니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42 AND stock >= 1;",
        stats: board(
          row("바깥 트랜잭션", "진행 중", "아직 커밋 전", "hot"),
          row("이 트랜잭션의 재고", "9", "밖에서는 10", "hot"),
          row("확정 주문", "0건", "저장 전"),
          row("커넥션", "같은 1개", "유지")
        ),
        acid: ["I"],
        tone: "work",
      },
      {
        name: "결제 참여",
        sub: "REQUIRED",
        layer: "spring",
        shape: "torus",
        title: "결제 메서드는 새 트랜잭션을 만들지 않는다",
        body: "PaymentService.charge도 REQUIRED입니다. 이미 열린 트랜잭션이 있으므로 거기에 참여합니다. 커넥션을 하나 더 빌리지 않고, 주문과 같은 연결로 결제 기록을 남깁니다.",
        code: "@Service\npublic class PaymentService {\n  @Transactional // REQUIRED\n  public void charge(Long bookId, int qty) {\n    paymentRepository.insertAttempt(bookId, qty);\n  }\n}",
        stats: board(
          row("바깥 트랜잭션", "진행 중", "그대로", "hot"),
          row("결제", "참여", "새 Tx 없음", "hot"),
          row("물리 트랜잭션", "1개", "논리적으로만 중첩"),
          row("커넥션", "같은 1개", "추가 대여 없음")
        ),
        acid: ["A"],
        tone: "work",
        callout: "전파는 다른 빈을 호출할 때만 적용됩니다. 같은 클래스에서 this.charge()로 부르면 프록시를 타지 않아 이 설정이 무시됩니다.",
      },
      {
        name: "결제 거절",
        sub: "예외",
        layer: "app",
        shape: "octa",
        title: "결제가 거절되면 참여한 작업도 같이 실패한다",
        body: "카드 승인이 거절되어 RuntimeException이 납니다. 결제 메서드가 자기만의 트랜잭션을 가진 것이 아니라 주문 트랜잭션에 참여 중이므로, 예외는 그 묶음 전체의 실패가 됩니다.",
        code: "throw new IllegalStateException(\"승인 거절\");\n// 참여 중인 트랜잭션의 rollback-only 표시",
        stats: board(
          row("바깥 트랜잭션", "롤백 예정", "예외가 밖으로", "bad"),
          row("결제 기록", "임시", "같이 취소될 예정", "bad"),
          row("확정 재고", "10", "아직 커밋 전"),
          row("커넥션", "같은 1개", "반납 전")
        ),
        acid: ["A"],
        tone: "danger",
      },
      {
        name: "함께 롤백",
        sub: "한 덩어리",
        layer: "db",
        shape: "octa",
        title: "재고 차감과 결제 시도가 함께 사라진다",
        body: "주문 메서드가 예외와 함께 끝나면 스프링은 그 트랜잭션을 롤백합니다. 재고는 10, 주문은 0, 결제 시도 기록도 없습니다. REQUIRED를 고른 이유가 이 결과입니다.",
        code: "// DataSourceTransactionManager\n// Rolling back JDBC transaction\n\n확정 재고 10\n주문 0건\n결제 시도 0건",
        stats: board(
          row("바깥 트랜잭션", "롤백됨", "전체 취소", "bad"),
          row("결제 기록", "0건", "같이 사라짐", "bad"),
          row("확정 재고", "10", "주문 전으로"),
          row("커넥션", "풀에 반환", "대여 종료")
        ),
        acid: ["A", "C"],
        tone: "danger",
        echoBack: true,
      },
    ],
  },
  {
    ...base,
    id: "prop-requires-new",
    title: "실패해도 기록은 남긴다",
    blurb: "주문은 취소돼도 '시도했다'는 이력은 저장해야 할 때. 옵션 이름은 REQUIRES_NEW.",
    tag: "REQUIRES_NEW",
    tone: "ok",
    steps: [
      {
        name: "주문 Tx A",
        sub: "바깥 시작",
        layer: "spring",
        shape: "box",
        title: "주문 트랜잭션 A를 연다",
        plain: "주문은 실패할 수 있습니다. 그래도 '결제 시도' 기록은 남아야 고객 문의에 답할 수 있습니다.",
        body: "주문 자체는 실패할 수 있습니다. 그래도 ‘누가 언제 결제를 시도했는지’는 남아 있어야 고객 문의에 답할 수 있습니다. 그 이력은 주문과 운명을 같이하면 안 됩니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {\n  bookRepository.decreaseStock(bookId, qty);\n  auditService.record(bookId, \"결제 시도\");\n  paymentService.charge(bookId, qty);\n}",
        stats: board(
          row("트랜잭션 A", "열림", "주문", "hot"),
          row("트랜잭션 B", "없음", "이력은 아직"),
          row("시도 이력", "0건", "audit_log"),
          row("확정 재고", "10", "커밋 전")
        ),
        acid: [],
        tone: "work",
        callout: "이럴 때 고릅니다. 본 작업이 롤백돼도 감사 로그, 알림 발송 이력, 실패 기록은 남겨야 할 때입니다.",
      },
      {
        name: "재고 차감",
        sub: "A 안에서",
        layer: "db",
        shape: "cylinder",
        title: "재고 차감은 A의 임시 변경이다",
        body: "재고 UPDATE는 트랜잭션 A에 들어 있습니다. 이 변경은 아직 확정이 아닙니다.",
        code: "UPDATE books SET stock = stock - 1\nWHERE id = 42 AND stock >= 1;\n-- 트랜잭션 A, 커밋 전",
        stats: board(
          row("트랜잭션 A", "진행 중", "재고는 임시", "hot"),
          row("A가 보는 재고", "9", "확정값은 10", "hot"),
          row("시도 이력", "0건", "아직"),
          row("A의 커넥션", "대여 중", "풀에서 1개")
        ),
        acid: ["I"],
        tone: "work",
      },
      {
        name: "A 일시정지",
        sub: "REQUIRES_NEW",
        layer: "spring",
        shape: "octa",
        title: "이력 저장이 A를 멈추고 트랜잭션 B를 연다",
        body: "AuditService.record는 REQUIRES_NEW입니다. 스프링은 A를 잠시 멈추고, 커넥션을 하나 더 빌려 완전히 다른 트랜잭션 B를 시작합니다. A의 재고 차감은 B에 보이지 않습니다.",
        code: "@Service\npublic class AuditService {\n  @Transactional(propagation = REQUIRES_NEW)\n  public void record(Long bookId, String action) {\n    auditRepository.insert(bookId, action);\n  }\n}",
        stats: board(
          row("트랜잭션 A", "일시정지", "재고 차감은 보류", "hot"),
          row("트랜잭션 B", "새로 열림", "다른 커넥션", "good"),
          row("물리 트랜잭션", "2개", "서로 독립"),
          row("커넥션", "2개 대여", "A 1 + B 1")
        ),
        acid: ["I"],
        tone: "work",
      },
      {
        name: "B 커밋",
        sub: "이력 확정",
        layer: "db",
        shape: "cone",
        title: "이력만 먼저 커밋된다",
        body: "record 메서드가 정상 종료되면 B만 커밋됩니다. 시도 이력 1건은 이미 확정입니다. 그 다음 A가 다시 깨어납니다. A는 아직 커밋되지 않았습니다.",
        code: "INSERT INTO audit_log (book_id, action)\nVALUES (42, '결제 시도');\nCOMMIT; -- B만\n\n-- A는 그대로 일시정지 해제",
        stats: board(
          row("트랜잭션 A", "다시 진행", "아직 미커밋", "hot"),
          row("트랜잭션 B", "커밋됨", "이미 확정", "good"),
          row("시도 이력", "1건", "롤백되지 않음", "good"),
          row("B의 커넥션", "풀에 반환", "A 커넥션은 유지")
        ),
        acid: ["D"],
        tone: "ok",
      },
      {
        name: "A 롤백",
        sub: "결제는 실패",
        layer: "app",
        shape: "octa",
        title: "결제가 거절되어 A만 롤백된다",
        body: "이어서 결제가 거절됩니다. A는 롤백되어 재고 차감이 취소됩니다. 이미 커밋된 B의 이력은 A가 취소해도 지워지지 않습니다.",
        code: "paymentService.charge(...);\n// throw new IllegalStateException(\"승인 거절\")\n// A rollback, B는 이미 commit",
        stats: board(
          row("트랜잭션 A", "롤백됨", "재고 차감 취소", "bad"),
          row("트랜잭션 B", "커밋 유지", "영향 없음", "good"),
          row("확정 재고", "10", "주문 0건"),
          row("시도 이력", "1건", "문의 대응용으로 남음", "good")
        ),
        acid: ["A"],
        tone: "danger",
        echoBack: true,
        callout: "안쪽 메서드가 예외를 던지면 바깥도 롤백됩니다. 이력은 그 전에 커밋되었기 때문에 남습니다. 이 호출도 반드시 다른 빈의 프록시를 통해야 합니다.",
      },
    ],
  },
  {
    ...base,
    id: "prop-nested",
    title: "쿠폰만 실패해도 주문은 산다",
    blurb: "부가 작업만 되돌리고 본 주문은 저장할 때. 옵션 이름은 NESTED.",
    tag: "NESTED",
    steps: [
      {
        name: "주문 Tx",
        sub: "바깥",
        layer: "spring",
        shape: "box",
        title: "주문은 반드시 남기고, 쿠폰은 되면 좋다",
        plain: "쿠폰 발급이 실패해도 이미 결제된 주문까지 취소하면 안 됩니다.",
        body: "첫 구매 쿠폰은 있으면 좋지만, 쿠폰 발급이 실패했다고 결제된 주문까지 취소하면 안 됩니다. 본 작업과 부가 작업의 실패 범위를 나누는 선택입니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {\n  Order order = orderRepository.save(new Order(bookId, qty));\n  try {\n    couponService.issueWelcome(order.getId());\n  } catch (RuntimeException ignored) {\n    // 쿠폰만 포기하고 주문은 계속\n  }\n  return order;\n}",
        stats: board(
          row("바깥 트랜잭션", "열림", "주문", "hot"),
          row("세이브포인트", "없음", "쿠폰 전"),
          row("주문", "임시 0", "곧 저장"),
          row("쿠폰", "0건", "부가 작업")
        ),
        acid: [],
        tone: "work",
        callout: "이럴 때 고릅니다. 실패해도 본 작업은 커밋하고, 부가 작업만 없던 일로 하고 싶을 때입니다.",
      },
      {
        name: "주문 저장",
        sub: "임시",
        layer: "db",
        shape: "cylinder",
        title: "주문 행을 바깥 트랜잭션에 넣는다",
        body: "주문 INSERT는 실행됐지만 커밋 전입니다. 재고도 이 트랜잭션 기준으로 9입니다. 쿠폰이 실패해도 이 주문은 살릴 예정입니다.",
        code: "UPDATE books SET stock = stock - 1 WHERE id = 42;\nINSERT INTO orders (book_id, qty) VALUES (42, 1);",
        stats: board(
          row("바깥 트랜잭션", "진행 중", "주문은 임시", "hot"),
          row("세이브포인트", "없음", "아직"),
          row("임시 주문", "1건", "확정 0건", "hot"),
          row("보는 재고", "9", "확정 재고 10", "hot")
        ),
        acid: ["A"],
        tone: "work",
      },
      {
        name: "세이브포인트",
        sub: "NESTED",
        layer: "spring",
        shape: "torus",
        title: "쿠폰 메서드는 새 트랜잭션 대신 저장점을 찍는다",
        body: "NESTED는 REQUIRES_NEW와 다릅니다. 커넥션을 하나 더 빌리지 않습니다. 같은 트랜잭션 안에 세이브포인트를 찍어, 이후 변경만 따로 되돌릴 수 있게 합니다.",
        code: "@Transactional(propagation = NESTED)\npublic void issueWelcome(Long orderId) {\n  couponRepository.insert(orderId, \"WELCOME\");\n}\n\n-- JDBC: SAVEPOINT coupon_try",
        stats: board(
          row("바깥 트랜잭션", "그대로", "커넥션도 같음", "hot"),
          row("세이브포인트", "찍힘", "쿠폰 시도 직전", "good"),
          row("물리 트랜잭션", "1개", "저장점만 중첩"),
          row("쿠폰", "0건", "INSERT 전")
        ),
        acid: ["A"],
        tone: "work",
        callout: "JDBC 트랜잭션 매니저의 세이브포인트로 동작합니다. JPA만 쓰는 프로젝트에서는 NESTED가 기대와 다르게 REQUIRED처럼 동작할 수 있어, 부분 취소가 꼭 필요하면 동작을 먼저 확인합니다.",
      },
      {
        name: "쿠폰만 실패",
        sub: "저장점 복귀",
        layer: "db",
        shape: "octa",
        title: "쿠폰 INSERT만 저장점 이전으로 돌아간다",
        body: "이미 받은 쿠폰이 있어 INSERT가 중복으로 실패합니다. 스프링은 바깥 트랜잭션 전체가 아니라 세이브포인트까지만 롤백합니다. 주문 INSERT는 저장점 이전에 있었으므로 임시 상태로 남습니다.",
        code: "INSERT INTO coupons (order_id, code)\nVALUES (1001, 'WELCOME');\n-- 중복 키 예외\nROLLBACK TO SAVEPOINT coupon_try;",
        stats: board(
          row("바깥 트랜잭션", "아직 살아 있음", "주문은 유지", "hot"),
          row("세이브포인트", "되감김", "쿠폰만 취소", "bad"),
          row("임시 주문", "1건", "그대로", "good"),
          row("쿠폰", "0건", "발급 포기", "bad")
        ),
        acid: ["A"],
        tone: "danger",
        echoBack: true,
      },
      {
        name: "주문 커밋",
        sub: "예외를 삼킴",
        layer: "db",
        shape: "cone",
        title: "주문 메서드가 예외를 잡고 커밋한다",
        body: "placeOrder는 쿠폰 예외를 잡았기 때문에 정상 종료됩니다. 스프링은 바깥 트랜잭션을 커밋합니다. 결과만 보면 주문은 있고 쿠폰은 없습니다. 손님의 구매는 성립합니다.",
        code: "COMMIT; -- 바깥 트랜잭션\n\n확정 재고 9\n주문 1건\n쿠폰 0건",
        stats: board(
          row("바깥 트랜잭션", "커밋됨", "주문 확정", "good"),
          row("쿠폰", "0건", "부가 작업만 실패"),
          row("확정 주문", "1건", "구매는 성립", "good"),
          row("확정 재고", "9", "차감 유지", "good")
        ),
        acid: ["A", "D"],
        tone: "ok",
        callout: "예외를 잡지 않으면 바깥까지 롤백되어, 쿠폰 때문에 주문도 사라집니다. NESTED의 부분 취소는 바깥이 그 예외를 처리하고 계속 갈 때 의미가 있습니다.",
      },
    ],
  },
  {
    ...base,
    id: "prop-not-supported",
    title: "카드사 호출은 묶음 밖으로",
    blurb: "느린 외부 호출 동안 DB 연결을 붙잡고 있으면 안 될 때. 옵션 이름은 NOT_SUPPORTED.",
    tag: "NOT_SUPPORTED",
    steps: [
      {
        name: "주문 Tx",
        sub: "DB 작업",
        layer: "spring",
        shape: "box",
        title: "재고 확인까지는 트랜잭션이 필요하다",
        plain: "재고를 깎는 동안에는 묶음이 필요합니다. 카드사 응답을 기다리는 1초까지 그 묶음에 넣으면 연결이 묶입니다.",
        body: "재고를 깎는 동안에는 트랜잭션이 있어야 합니다. 다만 카드사 API는 1~2초가 걸릴 수 있습니다. 그 시간 동안 DB 커넥션을 쥐고 있으면 풀이 쉽게 바닥납니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {\n  bookRepository.decreaseStock(bookId, qty);\n  paymentClient.charge(bookId, qty); // 카드사 HTTP\n  return orderRepository.save(new Order(bookId, qty));\n}",
        stats: board(
          row("트랜잭션", "열림", "재고 차감용", "hot"),
          row("카드사 호출", "아직", "트랜잭션 안"),
          row("보는 재고", "곧 9", "확정은 10"),
          row("커넥션", "대여 중", "풀 1개")
        ),
        acid: [],
        tone: "work",
        callout: "이럴 때 고릅니다. 외부 HTTP, 메일, 파일 전송처럼 느린 작업을 트랜잭션 한가운데 두면 안 될 때입니다.",
      },
      {
        name: "재고 차감",
        sub: "커밋 전",
        layer: "db",
        shape: "cylinder",
        title: "재고를 임시로 9로 만든다",
        body: "UPDATE까지는 트랜잭션 안에서 끝냅니다. 커넥션은 아직 이 트랜잭션이 들고 있습니다.",
        code: "UPDATE books SET stock = stock - 1\nWHERE id = 42 AND stock >= 1;",
        stats: board(
          row("트랜잭션", "진행 중", "임시 재고 9", "hot"),
          row("확정 재고", "10", "커밋 전"),
          row("주문", "0건", "승인 후 저장"),
          row("커넥션", "붙잡힘", "아직 반납 전", "bad")
        ),
        acid: ["I"],
        tone: "work",
      },
      {
        name: "트랜잭션 정지",
        sub: "NOT_SUPPORTED",
        layer: "spring",
        shape: "octa",
        title: "카드사 호출 전에 트랜잭션을 잠시 멈춘다",
        body: "PaymentClient.charge가 NOT_SUPPORTED이면 스프링은 현재 트랜잭션을 잠시 멈추고, 이 메서드는 트랜잭션 없이 실행합니다. 멈춰 있는 동안 커넥션은 풀로 돌아가 다른 요청이 쓸 수 있습니다.",
        code: "@Transactional(propagation = NOT_SUPPORTED)\npublic Approval charge(Long bookId, int qty) {\n  return cardCompany.httpPost(bookId, qty);\n}",
        stats: board(
          row("주문 트랜잭션", "일시정지", "SQL 없음", "hot"),
          row("이 메서드", "Tx 없음", "그냥 HTTP", "good"),
          row("보는 재고", "호출 중엔 무관", "DB를 안 씀"),
          row("커넥션", "풀에 반환", "다른 요청이 사용", "good")
        ),
        acid: [],
        tone: "work",
      },
      {
        name: "카드사",
        sub: "HTTP",
        layer: "web",
        shape: "sphere",
        title: "승인을 기다리는 동안 데이터베이스는 자유롭다",
        body: "카드사가 1초 뒤에 승인을 돌려줍니다. 이 1초 동안 주문 트랜잭션의 커넥션은 풀에 있습니다. 승인이 거절되면 여기서 예외가 나고, 재개된 주문 트랜잭션은 롤백됩니다.",
        code: "POST https://card.example/charge\n{ \"bookId\": 42, \"amount\": 18000 }\n\n200 { \"approved\": true }",
        stats: board(
          row("주문 트랜잭션", "일시정지", "승인 대기", "hot"),
          row("카드사", "승인", "HTTP 200", "good"),
          row("확정 재고", "10", "아직"),
          row("커넥션", "풀에서 대기", "붙잡지 않음", "good")
        ),
        acid: [],
        tone: "ok",
      },
      {
        name: "트랜잭션 재개",
        sub: "이어서 커밋",
        layer: "db",
        shape: "cone",
        title: "같은 트랜잭션이 깨어나 주문을 저장하고 커밋한다",
        body: "charge가 돌아오면 멈춰 두었던 주문 트랜잭션이 다시 시작되고 커넥션을 다시 빌립니다. 주문 INSERT 후 메서드가 끝나면 커밋됩니다. 재고 9와 주문 1건이 확정됩니다.",
        code: "INSERT INTO orders (book_id, qty) VALUES (42, 1);\nCOMMIT;\n\n확정 재고 9\n주문 1건",
        stats: board(
          row("주문 트랜잭션", "커밋됨", "재개 후 종료", "good"),
          row("카드 승인", "완료", "Tx 밖에서 받음", "good"),
          row("확정 주문", "1건", "구매 성립", "good"),
          row("커넥션", "풀에 반환", "대여 종료")
        ),
        acid: ["D"],
        tone: "ok",
      },
    ],
  },
  {
    ...base,
    id: "prop-supports",
    title: "조회는 있으면 같이, 없으면 혼자",
    blurb: "같은 재고 조회를 상품 화면에서도, 주문 도중에도 쓸 때. 옵션 이름은 SUPPORTS.",
    tag: "SUPPORTS",
    steps: [
      {
        name: "상품 화면",
        sub: "Tx 없음",
        layer: "web",
        shape: "sphere",
        title: "상품 페이지는 트랜잭션 없이 재고를 묻는다",
        plain: "상품 화면의 재고 숫자는 주문의 일부가 아닙니다. 묶음을 열지 않고 그냥 읽습니다.",
        body: "목록 화면의 재고 숫자는 주문 처리의 일부가 아닙니다. 트랜잭션을 일부러 열 이유가 없습니다. BookQuery.stock은 SUPPORTS라서, 트랜잭션이 없으면 그냥 SELECT만 합니다.",
        code: "@Transactional(propagation = SUPPORTS, readOnly = true)\npublic int stock(Long bookId) {\n  return bookRepository.getStock(bookId);\n}\n\n// 상품 페이지 → 트랜잭션 없음 → SELECT",
        stats: board(
          row("호출 위치", "상품 페이지", "트랜잭션 없음"),
          row("이 조회", "Tx 없이 실행", "참여할 대상이 없음"),
          row("읽은 재고", "10", "확정값", "good"),
          row("커넥션", "조회 후 반환", "길게 잡지 않음")
        ),
        acid: [],
        tone: "work",
        callout: "이럴 때 고릅니다. 같은 조회를 화면에서도 부르고, 주문 처리 중에도 부르고 싶을 때입니다.",
      },
      {
        name: "주문 시작",
        sub: "Tx 열림",
        layer: "spring",
        shape: "box",
        title: "주문 트랜잭션이 재고를 먼저 9로 본다",
        body: "잠시 뒤 다른 요청으로 주문이 시작됩니다. 재고 UPDATE가 커밋 전에 실행되어, 이 트랜잭션 안의 재고는 9, 확정 재고는 아직 10입니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {\n  bookRepository.decreaseStock(bookId, qty);\n  int left = bookQuery.stock(bookId);\n}",
        stats: board(
          row("주문 트랜잭션", "진행 중", "UPDATE 실행됨", "hot"),
          row("확정 재고", "10", "밖에서는 10"),
          row("이 Tx가 보는 재고", "9", "아직 임시", "hot"),
          row("조회 메서드", "곧 호출", "SUPPORTS")
        ),
        acid: ["I"],
        tone: "work",
      },
      {
        name: "조회 참여",
        sub: "SUPPORTS",
        layer: "spring",
        shape: "torus",
        title: "같은 메서드가 이번에는 주문 트랜잭션에 참여한다",
        body: "SUPPORTS는 트랜잭션이 있을 때만 참여합니다. 상품 페이지에서는 혼자 실행됐고, 주문 안에서는 그 트랜잭션의 커넥션으로 SELECT를 보냅니다. 그래서 방금 깎은 9를 읽습니다.",
        code: "SELECT stock FROM books WHERE id = 42;\n-- 주문 트랜잭션의 커넥션\n-- 결과: 9",
        stats: board(
          row("주문 트랜잭션", "진행 중", "조회가 참여", "hot"),
          row("읽은 재고", "9", "임시 변경이 보임", "hot"),
          row("확정 재고", "10", "다른 손님 기준"),
          row("커넥션", "주문과 동일", "새로 안 빌림", "good")
        ),
        acid: ["I"],
        tone: "work",
        callout: "트랜잭션 밖에서 새 커넥션으로 읽으면 아직 10이 나와, ‘재고가 남았다’고 잘못 판단할 수 있습니다. 주문 도중의 판단은 그 트랜잭션에 참여해야 합니다.",
      },
      {
        name: "판단",
        sub: "같은 기준",
        layer: "app",
        shape: "cone",
        title: "품절 여부를 이 주문이 본 재고로 판단한다",
        body: "조회가 9를 돌려줬으므로 주문 로직은 ‘아직 남음’이 아니라 ‘방금 1권을 확보한 뒤의 재고’를 기준으로 다음을 결정합니다. 화면용 조회와 주문용 조회를 메서드 두 개로 나누지 않아도 됩니다.",
        code: "if (bookQuery.stock(bookId) == 0) {\n  throw new IllegalStateException(\"품절\");\n}\n// 이번 호출의 결과는 9",
        stats: board(
          row("조회 결과", "9", "참여해서 읽음", "good"),
          row("상품 페이지였다면", "10", "Tx가 없었음"),
          row("주문", "이어서 저장", "같은 Tx"),
          row("전파", "SUPPORTS", "있으면 참여")
        ),
        acid: ["C"],
        tone: "ok",
      },
    ],
  },
  {
    ...base,
    id: "prop-mandatory",
    title: "혼자 호출되면 막는다",
    blurb: "재고 차감이 주문 묶음 없이 실행되면 안 될 때. 옵션 이름은 MANDATORY.",
    tag: "MANDATORY",
    tone: "danger",
    steps: [
      {
        name: "재고 메서드",
        sub: "MANDATORY",
        layer: "spring",
        shape: "box",
        title: "재고 차감은 반드시 누군가의 트랜잭션 안에 있어야 한다",
        plain: "재고만 혼자 저장되면, 주문이 실패해도 책이 사라집니다. 그래서 묶음 없이 부르면 아예 막습니다.",
        body: "decreaseStock이 혼자 실행되면 그 한 문장만 바로 확정됩니다. 주문 저장이 실패해도 재고는 이미 줄어 있습니다. 그래서 이 메서드는 주문 트랜잭션에 참여할 때만 허용하고, 혼자 부르면 아예 막습니다.",
        code: "@Transactional(propagation = MANDATORY)\npublic void decreaseStock(Long bookId, int qty) {\n  bookRepository.decrease(bookId, qty);\n}",
        stats: board(
          row("메서드", "MANDATORY", "기존 Tx 필수"),
          row("허용되는 호출", "주문 Tx 안", "있으면 참여"),
          row("막히는 호출", "직접 실행", "Tx가 없으면 예외", "bad"),
          row("재고", "10", "아직 SQL 없음")
        ),
        acid: ["A"],
        tone: "work",
        callout: "이럴 때 고릅니다. 이 메서드가 단독으로 커밋되면 데이터가 깨지므로, 호출자가 트랜잭션을 열었는지 강제하고 싶을 때입니다.",
      },
      {
        name: "배치 실수",
        sub: "Tx 없음",
        layer: "app",
        shape: "octa",
        title: "배치가 주문 서비스를 거치지 않고 직접 호출한다",
        body: "재고를 맞추는 배치가 BookStock.decreaseStock만 호출합니다. 이 호출 경로에는 @Transactional이 없습니다. REQUIRED였다면 배치가 자기 트랜잭션을 새로 열어 재고만 확정했을 것입니다.",
        code: "public void adjust() {\n  bookStock.decreaseStock(42L, 1); // 주문 Tx 없음\n}",
        stats: board(
          row("호출자", "재고 배치", "트랜잭션 없음", "bad"),
          row("주문 서비스", "안 거침", "묶음이 없음"),
          row("재고", "10", "아직"),
          row("커넥션", "아직 없음", "SQL 전")
        ),
        acid: [],
        tone: "danger",
      },
      {
        name: "즉시 예외",
        sub: "SQL 없음",
        layer: "spring",
        shape: "octa",
        title: "트랜잭션이 없으므로 SQL을 보내기 전에 예외가 난다",
        body: "MANDATORY는 참여할 트랜잭션이 없으면 IllegalTransactionStateException을 던집니다. UPDATE는 실행되지 않습니다. 잘못된 호출이 재고를 바꾸지 못하고, 스택 트레이스로 호출 경로가 드러납니다.",
        code: "// IllegalTransactionStateException\n// No existing transaction found\n// for transaction marked with propagation 'mandatory'",
        stats: board(
          row("예외", "즉시 발생", "SQL 이전", "bad"),
          row("UPDATE", "실행 안 됨", "재고 변화 없음", "good"),
          row("확정 재고", "10", "그대로", "good"),
          row("주문", "0건", "배치가 만들지 않음")
        ),
        acid: ["C"],
        tone: "danger",
        callout: "주문 서비스의 트랜잭션 안에서 이 메서드를 부르면 예외 없이 그 트랜잭션에 참여합니다. MANDATORY는 정상 흐름을 나누는 옵션이 아니라, 잘못된 단독 호출을 막는 가드입니다.",
      },
    ],
  },
  {
    ...base,
    id: "prop-never",
    title: "주문 안에 끼면 거절한다",
    blurb: "무거운 매출 조회가 주문 묶음에 들어가면 안 될 때. 옵션 이름은 NEVER.",
    tag: "NEVER",
    tone: "danger",
    steps: [
      {
        name: "주문 Tx",
        sub: "진행 중",
        layer: "spring",
        shape: "box",
        title: "주문 트랜잭션이 재고를 붙잡고 있다",
        plain: "주문 처리 중에 하루 매출 집계까지 넣으면, 집계가 끝날 때까지 재고 잠금이 안 풀립니다.",
        body: "주문이 진행 중이면 그 트랜잭션은 재고 행을 건드린 뒤라 커밋 전까지 커넥션을 들고 있습니다. 여기에 하루치 매출을 집계하는 무거운 조회가 끼면, 집계가 끝날 때까지 그 커넥션과 잠금이 풀리지 않습니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {\n  bookRepository.decreaseStock(bookId, qty);\n  reportService.dailySales(); // 실수로 끼어든 호출\n}",
        stats: board(
          row("주문 트랜잭션", "진행 중", "커넥션 점유", "hot"),
          row("리포트", "호출됨", "여기 있으면 위험", "bad"),
          row("확정 재고", "10", "임시로는 9"),
          row("잠금", "재고 행", "커밋 전까지")
        ),
        acid: [],
        tone: "work",
        callout: "이럴 때 고릅니다. 이 메서드가 트랜잭션에 들어가는 것 자체를 버그로 보고, 호출한 즉시 실패시키고 싶을 때입니다.",
      },
      {
        name: "리포트",
        sub: "NEVER",
        layer: "spring",
        shape: "octa",
        title: "리포트 메서드는 트랜잭션이 있으면 거절한다",
        body: "dailySales는 NEVER입니다. 진행 중인 트랜잭션이 보이면 집계 쿼리를 실행하지 않고 IllegalTransactionStateException을 던집니다. 무거운 SELECT가 주문 트랜잭션에 합류하는 일을 구조적으로 막습니다.",
        code: "@Transactional(propagation = NEVER, readOnly = true)\npublic Sales dailySales() {\n  return salesRepository.sumToday();\n}",
        stats: board(
          row("주문 트랜잭션", "진행 중", "리포트가 발견", "hot"),
          row("리포트", "거절", "쿼리 실행 안 함", "bad"),
          row("집계 SELECT", "없음", "락을 더 안 잡음", "good"),
          row("전파", "NEVER", "있으면 예외")
        ),
        acid: [],
        tone: "danger",
      },
      {
        name: "호출 위치",
        sub: "Tx 밖",
        layer: "web",
        shape: "sphere",
        title: "리포트는 주문 밖, 화면이나 스케줄러에서 호출한다",
        body: "관리자 화면이나 새벽 배치처럼 트랜잭션이 없는 진입점에서 부르면 NEVER는 그냥 실행됩니다. 집계는 자기 SELECT만 하고 커넥션을 바로 돌려줍니다. 주문 처리와 시간이 겹어도 주문의 잠금을 연장하지 않습니다.",
        code: "@GetMapping(\"/admin/sales/today\")\npublic Sales today() {\n  return reportService.dailySales(); // 이 컨트롤러에는 Tx 없음\n}",
        stats: board(
          row("호출 위치", "관리자 화면", "트랜잭션 없음", "good"),
          row("리포트", "실행", "NEVER 통과", "good"),
          row("주문 트랜잭션", "무관", "이 요청과 분리"),
          row("커넥션", "조회 후 반환", "주문을 기다리지 않음")
        ),
        acid: [],
        tone: "ok",
        callout: "주문 메서드 안에서 예외를 삼키지 않으면 그 예외 때문에 주문까지 롤백됩니다. NEVER는 데이터를 나누는 옵션이 아니라, 잘못된 호출 위치를 바로 드러내는 옵션입니다.",
      },
    ],
  },
];
