import { propagationScenarios } from "./propagation.js";
import { externalDbScenarios } from "./external-db.js";

const stockOk = { committedStock: 10, viewStock: 10, committedOrders: 0, pendingOrders: 0 };
const stockTemp = { committedStock: 10, viewStock: 9, committedOrders: 0, pendingOrders: 0 };
const orderTemp = { committedStock: 10, viewStock: 9, committedOrders: 0, pendingOrders: 1 };
const orderDone = { committedStock: 9, viewStock: 9, committedOrders: 1, pendingOrders: 0 };
const stockLost = { committedStock: 9, viewStock: 9, committedOrders: 0, pendingOrders: 0 };

export const scenarios = [
  {
    id: "no-tx",
    group: "1. 먼저 개념",
    title: "묶지 않으면",
    blurb: "한 줄이 끝나자마자 저장됩니다. 뒤가 실패해도 앞은 남아요.",
    tag: "문제",
    tone: "danger",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "책 한 권을 주문한다",
        plain: "창고에는 책이 10권, 주문은 0건입니다. 아직 아무것도 안 바뀌었습니다.",
        body: "손님이 주문 버튼을 눌렀을 뿐입니다. 데이터베이스는 재고도 주문도 고치지 않았습니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }\n\n-- books.stock = 10\n-- orders = 0건",
        ...stockOk,
        tx: "없음",
        connection: "아직 쿼리 없음",
        acid: [],
        tone: "work",
      },
      {
        name: "서버",
        sub: "주문 처리",
        layer: "app",
        shape: "box",
        title: "서버가 SQL을 하나씩 보낸다",
        plain: "묶지 않으면 SQL 한 줄이 끝나는 즉시 저장됩니다. 이 기본 동작을 자동 커밋이라고 합니다.",
        body: "재고를 줄이는 줄과 주문을 넣는 줄이 따로 저장됩니다. 나중 줄이 실패해도 앞 줄만 골라 취소할 방법이 없습니다.",
        code: "-- 트랜잭션을 시작하지 않음\n-- 연결의 autocommit = true",
        ...stockOk,
        tx: "없음",
        connection: "문장마다 자동 커밋",
        acid: ["A"],
        tone: "work",
        callout: "실무에서 자동 커밋이 켜진 채로 재고와 주문을 따로 실행하면, 아래 단계에서 보는 사고가 납니다.",
      },
      {
        name: "재고 차감",
        sub: "UPDATE 즉시 확정",
        layer: "db",
        shape: "cylinder",
        title: "재고가 곧바로 9가 된다",
        plain: "재고만 먼저 9권이 되었습니다. 주문 장부에는 아직 아무것도 없습니다.",
        body: "다른 손님도 이제 9권을 봅니다. 주문은 아직 시작도 안 했는데 창고 숫자만 바뀐 상태입니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;\n-- 1 row, 즉시 커밋",
        ...stockLost,
        tx: "없음",
        connection: "이 문장만 확정하고 종료",
        acid: ["A", "I"],
        tone: "danger",
      },
      {
        name: "결제 거절",
        sub: "주문은 실패",
        layer: "app",
        shape: "octa",
        title: "결제가 거절되어 주문을 못 남긴다",
        plain: "카드가 거절돼서 주문은 없습니다. 그런데 재고는 이미 9입니다. 책 한 권이 사라졌습니다.",
        body: "요청은 실패로 끝났지만, 앞에서 저장된 재고 감소는 그대로입니다. 이게 트랜잭션 없이 주문을 처리할 때 생기는 사고입니다.",
        code: "결제 승인 실패\n-- INSERT는 실행하지 않음\n\n확정 재고 9\n주문 0건",
        ...stockLost,
        tx: "없음",
        connection: "되돌릴 묶음이 없음",
        acid: ["A", "C"],
        tone: "danger",
        callout: "이 틈이 트랜잭션이 필요한 이유입니다. 같은 실패를 ‘롤백으로 취소’ 시나리오에서 보면 재고가 10으로 남습니다.",
      },
    ],
  },
  {
    id: "commit",
    group: "1. 먼저 개념",
    title: "성공하면 한 번에 저장",
    blurb: "재고와 주문을 묶었다가, 둘 다 끝나면 한꺼번에 확정합니다.",
    tag: "성공",
    tone: "ok",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "같은 주문이 들어온다",
        plain: "같은 주문입니다. 이번에는 재고 감소와 주문 저장을 하나로 묶습니다.",
        body: "묶음의 시작을 BEGIN, 확정을 커밋, 취소를 롤백이라고 부릅니다. 커밋 전에는 둘 다 임시입니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "대기",
        acid: [],
        tone: "work",
      },
      {
        name: "BEGIN",
        sub: "작업 묶음 시작",
        layer: "db",
        shape: "torus",
        title: "지금부터는 임시라고 표시한다",
        plain: "BEGIN은 '지금부터 바꾸는 내용은 아직 임시'라는 시작 신호입니다.",
        body: "다른 손님에게는 재고가 아직 10입니다. 이 주문 작업 안에서만 이후 변경이 보입니다. 이렇게 밖에 안 보이게 하는 성질을 격리라고 합니다.",
        code: "BEGIN;\n-- 이 연결의 autocommit을 끄고\n-- 이후 SQL을 한 묶음으로 취급",
        ...stockOk,
        tx: "진행 중",
        connection: "트랜잭션에 고정",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "아직 임시",
        layer: "db",
        shape: "cylinder",
        title: "재고를 줄였지만 아직 임시이다",
        plain: "줄이라는 명령은 실행됐습니다. 다만 밖에서는 아직 10권입니다.",
        body: "이 묶음 안에서는 재고가 9로 보입니다. 실행된 것과 모두에게 확정된 것은 다릅니다. 확정은 커밋 때 일어납니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["A", "I"],
        tone: "work",
        callout: "WHERE stock >= 1 은 재고가 0 아래로 내려가는 주문을 막습니다. 일관성을 애플리케이션과 데이터베이스가 함께 지키는 지점입니다.",
      },
      {
        name: "주문 저장",
        sub: "아직 임시",
        layer: "db",
        shape: "cylinder",
        title: "주문도 같은 임시 묶음에 넣는다",
        plain: "주문 1건이 생겼지만, 밖에서는 아직 주문이 없습니다.",
        body: "재고 9와 주문 1건은 둘 다 이 묶음 안에만 있습니다. 커밋하면 같이 확정되고, 롤백하면 같이 사라집니다.",
        code: "INSERT INTO orders (book_id, qty)\nVALUES (42, 1);",
        ...orderTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "COMMIT",
        sub: "모두 확정",
        layer: "db",
        shape: "cone",
        title: "커밋하는 순간 둘 다 진짜가 된다",
        plain: "커밋은 '이제 진짜'입니다. 재고 9권, 주문 1건이 모두에게 확정됩니다.",
        body: "이 다음부터는 서버가 꺼져도 주문은 데이터베이스에 남습니다. 이렇게 남기는 성질을 지속성이라고 합니다.",
        code: "COMMIT;",
        ...orderDone,
        tx: "커밋됨",
        connection: "풀로 반환 가능",
        acid: ["A", "D"],
        tone: "ok",
      },
    ],
  },
  {
    id: "rollback",
    group: "1. 먼저 개념",
    title: "실패하면 전부 취소",
    blurb: "중간에 결제가 거절되면, 줄어든 재고까지 주문 전으로 되돌립니다.",
    tag: "실패",
    tone: "danger",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "다시 같은 주문",
        plain: "또 책 1권을 삽니다. 이번엔 중간에 카드가 거절됩니다.",
        body: "재고 10, 주문 0에서 시작합니다. 재고를 줄이는 것까지는 앞의 성공 흐름과 같고, 그 다음이 다릅니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "대기",
        acid: [],
        tone: "work",
      },
      {
        name: "BEGIN",
        sub: "작업 묶음 시작",
        layer: "db",
        shape: "torus",
        title: "먼저 묶음부터 연다",
        plain: "실패할 수도 있는 일이면, 저장하기 전에 묶음부터 엽니다.",
        body: "BEGIN 이후의 재고 감소는 임시입니다. 결제가 거절되면 이 임시 변경을 통째로 버릴 수 있습니다.",
        code: "BEGIN;",
        ...stockOk,
        tx: "진행 중",
        connection: "트랜잭션에 고정",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "임시 반영",
        layer: "db",
        shape: "cylinder",
        title: "재고를 임시로 9로 본다",
        plain: "이 주문 안에서는 재고가 9입니다. 다른 손님은 아직 10권을 봅니다.",
        body: "UPDATE는 실행됐습니다. 확정 재고는 10입니다. 커밋하기 전에는 창고의 공식 숫자가 바뀌지 않습니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "결제 거절",
        sub: "예외 발생",
        layer: "app",
        shape: "octa",
        title: "결제가 거절된다",
        plain: "카드가 거절됐습니다. 여기서 저장하면 재고만 9로 확정됩니다.",
        body: "그래서 저장(커밋)하지 않습니다. 취소(롤백)를 골라, 재고 감소를 임시인 채로 버립니다.",
        code: "결제 승인 실패\n-- COMMIT 하지 않음",
        ...stockTemp,
        tx: "진행 중",
        connection: "아직 묶음 안",
        acid: ["A"],
        tone: "danger",
      },
      {
        name: "ROLLBACK",
        sub: "전부 취소",
        layer: "db",
        shape: "octa",
        title: "롤백하면 재고 10으로 돌아온다",
        plain: "롤백은 '없었던 일'입니다. 재고는 다시 10권, 주문은 0건입니다.",
        body: "UPDATE가 실행됐다는 사실은 확정 데이터에 남지 않습니다. 손님에게는 실패라고 알리고, 창고는 주문 전과 같습니다.",
        code: "ROLLBACK;",
        ...stockOk,
        tx: "롤백됨",
        connection: "풀로 반환 가능",
        acid: ["A", "C"],
        tone: "danger",
        echoBack: true,
        callout: "손님에게는 실패를 알립니다. 데이터는 주문 요청 전과 같습니다. 트랜잭션 없이 시나리오에서는 이 자리에서 재고가 9로 남았습니다.",
      },
    ],
  },
  {
    id: "spring-ok",
    group: "2. 스프링에서는",
    title: "메서드가 끝나면 저장",
    blurb: "개발자가 BEGIN을 쓰지 않아도, 서비스 메서드가 끝나면 스프링이 커밋합니다.",
    tag: "실무",
    tone: "ok",
    steps: [
      {
        name: "브라우저",
        sub: "POST /orders",
        layer: "web",
        shape: "sphere",
        title: "화면이 주문을 보낸다",
        plain: "주문 버튼이 서버에 '이 책 1권'이라고 보냅니다. 아직 창고는 그대로입니다.",
        body: "스프링을 아직 몰라도 됩니다. 화면은 요청만 보내고, 재고와 주문을 묶는 경계는 곧 나올 서비스 메서드 하나입니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "컨트롤러",
        sub: "OrderController",
        layer: "web",
        shape: "box",
        title: "접수 창구는 시키기만 한다",
        plain: "컨트롤러는 접수 창구입니다. 재고를 깎는 계산은 하지 않습니다.",
        body: "창구는 주문 서비스의 placeOrder를 호출하고, 끝난 결과를 화면에 돌려줍니다. 묶음의 시작과 끝은 서비스 메서드에 둡니다. 창구마다 트랜잭션을 열면 범위가 불필요하게 넓어집니다.",
        code: "@PostMapping(\"/orders\")\npublic Order place(@RequestBody OrderRequest req) {\n  return orderService.placeOrder(req.bookId(), req.qty());\n}",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "프록시",
        sub: "호출을 가로챔",
        layer: "spring",
        shape: "octa",
        title: "문지기가 먼저 받는다",
        plain: "스프링은 주문 코드 앞에 문지기를 세웁니다. 문지기가 묶음을 연 다음에야 주문이 시작됩니다.",
        body: "이 문지기를 프록시라고 부릅니다. 컨트롤러가 가지고 있는 주문 서비스는 진짜 객체가 아니라 프록시입니다. @Transactional이 붙은 메서드는 프록시가 먼저 받습니다.",
        code: "@Configuration\n@EnableTransactionManagement\nclass AppConfig {\n  @Bean\n  PlatformTransactionManager txManager(DataSource ds) {\n    return new DataSourceTransactionManager(ds);\n  }\n}",
        ...stockOk,
        tx: "시작 직전",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
        callout: "같은 클래스 안에서 this.placeOrder()로 부르면 문지기를 안 거칩니다. 그러면 @Transactional이 무시됩니다. 트랜잭션이 필요한 메서드는 다른 객체가 호출하게 둡니다. 스프링 부트에서 JPA를 쓰면 이 문지기 설정은 대개 자동입니다.",
      },
      {
        name: "트랜잭션 시작",
        sub: "getTransaction",
        layer: "spring",
        shape: "torus",
        title: "DB 연결을 빌리고 묶음을 연다",
        plain: "문지기가 연결 보관함에서 연결을 하나 빌립니다. 그리고 '이 연결의 SQL은 한 묶음'이라고 표시합니다.",
        body: "보관함을 커넥션 풀, 빌린 연결을 커넥션이라고 합니다. 개발자가 BEGIN을 쓰지 않아도 스프링이 자동 커밋을 끄고 트랜잭션을 시작합니다. 이 역할을 트랜잭션 매니저가 합니다.",
        code: "// PlatformTransactionManager\nTransactionStatus getTransaction(\n    TransactionDefinition definition);\n\n// 기본 전파 속성 REQUIRED\n// 이미 열린 트랜잭션이 있으면 거기에 참여",
        ...stockOk,
        tx: "진행 중",
        connection: "풀에서 빌려 사용 중",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "서비스 본문",
        sub: "placeOrder",
        layer: "app",
        shape: "box",
        title: "이제야 재고와 주문을 처리한다",
        plain: "진짜 주문 코드가 실행됩니다. 재고는 9, 주문은 1건이지만 둘 다 아직 임시입니다.",
        body: "재고를 줄이는 SQL과 주문을 넣는 SQL은 방금 빌린 그 연결로 나갑니다. 밖에서는 재고 10, 주문 0입니다.",
        code: "@Service\npublic class OrderService {\n  @Transactional\n  public Order placeOrder(Long bookId, int qty) {\n    bookRepository.decreaseStock(bookId, qty);\n    return orderRepository.save(new Order(bookId, qty));\n  }\n}",
        ...orderTemp,
        tx: "진행 중",
        connection: "같은 커넥션으로 SQL",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "커밋",
        sub: "commit()",
        layer: "spring",
        shape: "cone",
        title: "에러 없이 끝나면 스프링이 저장한다",
        plain: "메서드가 끝까지 가면 스프링이 커밋합니다. 재고 9와 주문 1건이 확정됩니다.",
        body: "개발자가 COMMIT을 호출하지 않습니다. 메서드가 정상적으로 끝나는 것 자체가 저장 신호입니다.",
        code: "void commit(TransactionStatus status);\n\n// 메서드가 정상 반환되면\n// DataSourceTransactionManager가 COMMIT",
        ...orderDone,
        tx: "커밋됨",
        connection: "커밋 직후",
        acid: ["A", "D"],
        tone: "ok",
      },
      {
        name: "커넥션 반환",
        sub: "풀로 복귀",
        layer: "db",
        shape: "cylinder",
        title: "연결을 돌려주고 성공을 알린다",
        plain: "빌린 연결을 보관함에 돌려주고, 화면에는 주문 성공을 보여 줍니다.",
        body: "요청마다 연결을 새로 만들지 않고 돌려 씁니다. 그래서 트랜잭션이 끝나면 반드시 풀로 반환합니다.",
        code: "// DataSourceUtils\n// Returning JDBC Connection to DataSource\n\nHTTP 200\n{ \"orderId\": 1001, \"bookId\": 42, \"qty\": 1 }",
        ...orderDone,
        tx: "커밋됨",
        connection: "풀에 반환",
        acid: ["D"],
        tone: "ok",
      },
    ],
  },
  {
    id: "spring-fail",
    group: "2. 스프링에서는",
    title: "에러가 나면 전부 취소",
    blurb: "메서드 밖으로 예외가 나오면, 스프링이 그 묶음을 롤백합니다.",
    tag: "롤백",
    tone: "danger",
    steps: [
      {
        name: "브라우저",
        sub: "POST /orders",
        layer: "web",
        shape: "sphere",
        title: "다시 주문 요청",
        plain: "요청은 성공 때와 같습니다. 이번엔 카드가 거절됩니다.",
        body: "화면, 창구, 문지기 순서는 같습니다. 차이는 주문 코드 안에서 결제가 실패한다는 점뿐입니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "프록시",
        sub: "트랜잭션 경계",
        layer: "spring",
        shape: "octa",
        title: "문지기가 먼저 묶음을 연다",
        plain: "실패하는 경우에도 문지기가 본문보다 먼저 트랜잭션을 엽니다.",
        body: "연결을 빌리고 자동 커밋을 끈 뒤에야 재고를 줄이는 코드가 실행됩니다. 그래서 실패하면 그 감소를 되돌릴 수 있습니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {",
        ...stockOk,
        tx: "진행 중",
        connection: "풀에서 빌려 사용 중",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "커밋 전 SQL",
        layer: "db",
        shape: "cylinder",
        title: "재고를 줄였지만 아직 임시이다",
        plain: "재고를 줄이라는 SQL은 나갔습니다. 그래도 밖에서는 아직 10권입니다.",
        body: "'이미 UPDATE 했으니 저장된 것'이 아닙니다. 커밋 전에는 이 묶음 안에서만 9입니다.",
        code: "bookRepository.decreaseStock(bookId, qty);\n// UPDATE는 실행됨, COMMIT 전",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 커넥션",
        acid: ["A", "I"],
        tone: "work",
      },
      {
        name: "런타임 예외",
        sub: "결제 실패",
        layer: "app",
        shape: "octa",
        title: "결제 실패가 예외로 전달된다",
        plain: "카드 거절은 실행 중 예외로 올라옵니다. 스프링은 이런 예외를 실패로 보고 롤백합니다.",
        body: "실행 중 예외를 RuntimeException이라고 합니다. 컴파일할 때 꼭 처리하라고 표시된 체크 예외는, 기본으로는 롤백하지 않고 커밋합니다.",
        code: "paymentClient.charge(bookId, qty);\n// throw new IllegalStateException(\"승인 거절\");\n\n// 체크 예외까지 롤백하려면\n// @Transactional(rollbackFor = Exception.class)",
        ...stockTemp,
        tx: "진행 중",
        connection: "아직 반납 전",
        acid: ["A"],
        tone: "danger",
        callout: "예외를 catch로 삼키고 정상적으로 끝나면, 스프링은 실패로 보지 않고 커밋합니다. 롤백이 필요하면 예외가 메서드 밖으로 나가게 두세요. 체크 예외까지 롤백하려면 rollbackFor를 지정합니다.",
      },
      {
        name: "롤백",
        sub: "rollback()",
        layer: "spring",
        shape: "octa",
        title: "문지기가 롤백을 호출한다",
        plain: "예외가 문지기까지 올라오면 스프링이 롤백합니다. 재고는 다시 10입니다.",
        body: "줄어들었던 재고는 확정되지 않습니다. 주문도 없습니다. 로그에는 rollback이라는 단어가 남습니다.",
        code: "void rollback(TransactionStatus status);\n\n// RuntimeException → 롤백 후 예외를 다시 던짐",
        ...stockOk,
        tx: "롤백됨",
        connection: "롤백 직후",
        acid: ["A", "C"],
        tone: "danger",
        echoBack: true,
      },
      {
        name: "응답",
        sub: "연결 반환",
        layer: "web",
        shape: "sphere",
        title: "연결을 돌려주고 실패를 알린다",
        plain: "화면에는 실패가 보이고, 창고는 주문 전과 같습니다.",
        body: "롤백 뒤에도 연결은 보관함에 돌아갑니다. 예외는 없어지지 않고 창구까지 전달되어, 손님은 실패 응답을 받습니다.",
        code: "// Returning JDBC Connection to DataSource\n// 예외가 $Proxy.placeOrder 밖으로 전달\n\nHTTP 500\n재고 10 · 주문 0건",
        ...stockOk,
        tx: "롤백됨",
        connection: "풀에 반환",
        acid: ["A"],
        tone: "danger",
      },
    ],
  },
  ...propagationScenarios,
  ...externalDbScenarios,
];
