import { propagationScenarios } from "./propagation.js";

const stockOk = { committedStock: 10, viewStock: 10, committedOrders: 0, pendingOrders: 0 };
const stockTemp = { committedStock: 10, viewStock: 9, committedOrders: 0, pendingOrders: 0 };
const orderTemp = { committedStock: 10, viewStock: 9, committedOrders: 0, pendingOrders: 1 };
const orderDone = { committedStock: 9, viewStock: 9, committedOrders: 1, pendingOrders: 0 };
const stockLost = { committedStock: 9, viewStock: 9, committedOrders: 0, pendingOrders: 0 };

export const scenarios = [
  {
    id: "no-tx",
    group: "데이터베이스",
    title: "트랜잭션 없이",
    blurb: "문장마다 바로 반영되면 앞선 수정만 남습니다.",
    tag: "문제",
    tone: "danger",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "책 한 권을 주문한다",
        body: "재고가 10권인 책을 1권 사겠다는 요청이 들어옵니다. 데이터베이스는 아직 아무 행도 고치지 않았습니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }\n\n-- books.stock = 10\n-- orders = 0건",
        ...stockOk,
        tx: "없음",
        connection: "아직 쿼리 없음",
        acid: [],
        tone: "work",
      },
      {
        name: "서버",
        sub: "주문 처리",
        layer: "app",
        shape: "box",
        title: "서버가 SQL을 하나씩 보낸다",
        body: "트랜잭션을 열지 않으면 각 SQL은 끝나는 즉시 확정됩니다. 데이터베이스 기본 동작인 자동 커밋입니다. 뒤에 실패해도 앞 문장을 묶어 취소할 방법이 없습니다.",
        code: "-- 트랜잭션을 시작하지 않음\n-- 연결의 autocommit = true",
        ...stockOk,
        tx: "없음",
        connection: "문장마다 자동 커밋",
        acid: ["A"],
        tone: "work",
        callout: "실무에서 자동 커밋이 켜진 채로 재고와 주문을 따로 실행하면, 아래 단계에서 보는 사고가 납니다.",
      },
      {
        name: "재고 차감",
        sub: "UPDATE 즉시 확정",
        layer: "db",
        shape: "cylinder",
        title: "재고가 곧바로 9가 된다",
        body: "UPDATE가 성공하는 순간 확정 재고가 10에서 9로 바뀝니다. 주문 행은 아직 없습니다. 다른 손님도 이제 재고 9권을 봅니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;\n-- 1 row, 즉시 커밋",
        ...stockLost,
        tx: "없음",
        connection: "이 문장만 확정하고 종료",
        acid: ["A", "I"],
        tone: "danger",
      },
      {
        name: "결제 거절",
        sub: "주문은 실패",
        layer: "app",
        shape: "octa",
        title: "결제가 거절되어 주문을 못 남긴다",
        body: "카드 승인이 거절되어 주문 INSERT는 실행되지 않았습니다. 요청은 실패인데 재고만 이미 줄었습니다. 창고에는 9권, 주문 장부에는 0건. 책 한 권이 설명 없이 사라진 상태입니다.",
        code: "결제 승인 실패\n-- INSERT는 실행하지 않음\n\n확정 재고 9\n주문 0건",
        ...stockLost,
        tx: "없음",
        connection: "되돌릴 묶음이 없음",
        acid: ["A", "C"],
        tone: "danger",
        callout: "이 틈이 트랜잭션이 필요한 이유입니다. 같은 실패를 ‘롤백으로 취소’ 시나리오에서 보면 재고가 10으로 남습니다.",
      },
    ],
  },
  {
    id: "commit",
    group: "데이터베이스",
    title: "커밋으로 확정",
    blurb: "BEGIN부터 COMMIT까지가 하나의 작업입니다.",
    tag: "성공",
    tone: "ok",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "같은 주문이 들어온다",
        body: "상황은 같습니다. 재고 10권인 책을 1권 삽니다. 이번에는 서버가 두 SQL을 하나의 트랜잭션으로 묶습니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "대기",
        acid: [],
        tone: "work",
      },
      {
        name: "BEGIN",
        sub: "작업 묶음 시작",
        layer: "db",
        shape: "torus",
        title: "트랜잭션을 연다",
        body: "BEGIN 이후의 변경은 이 연결 안에서만 보입니다. 커밋 전에는 다른 손님의 조회에 섞이지 않는 것이 일반적인 격리 수준입니다. 확정 재고는 여전히 10입니다.",
        code: "BEGIN;\n-- 이 연결의 autocommit을 끄고\n-- 이후 SQL을 한 묶음으로 취급",
        ...stockOk,
        tx: "진행 중",
        connection: "트랜잭션에 고정",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "아직 임시",
        layer: "db",
        shape: "cylinder",
        title: "재고 UPDATE는 실행됐지만 임시이다",
        body: "쿼리는 이미 실행되어 이 트랜잭션은 재고 9를 봅니다. 그러나 커밋 전이라 확정 재고는 10입니다. ‘실행’과 ‘확정’은 다릅니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["A", "I"],
        tone: "work",
        callout: "WHERE stock >= 1 은 재고가 0 아래로 내려가는 주문을 막습니다. 일관성을 애플리케이션과 데이터베이스가 함께 지키는 지점입니다.",
      },
      {
        name: "주문 저장",
        sub: "아직 임시",
        layer: "db",
        shape: "cylinder",
        title: "주문 INSERT도 같은 묶음에 넣는다",
        body: "주문 1건이 이 트랜잭션 안에 생겼습니다. 밖에서는 아직 주문이 없고 재고도 10입니다. 커밋하거나 롤백하기 전까지는 둘 다 임시 상태입니다.",
        code: "INSERT INTO orders (book_id, qty)\nVALUES (42, 1);",
        ...orderTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "COMMIT",
        sub: "모두 확정",
        layer: "db",
        shape: "cone",
        title: "커밋하는 순간 둘 다 확정된다",
        body: "COMMIT은 임시 변경을 한꺼번에 확정합니다. 재고 9, 주문 1건이 이제 모두의 기준이 됩니다. 이 시점 이후에는 애플리케이션이 멈춰도 주문은 데이터베이스에 남습니다.",
        code: "COMMIT;",
        ...orderDone,
        tx: "커밋됨",
        connection: "풀로 반환 가능",
        acid: ["A", "D"],
        tone: "ok",
      },
    ],
  },
  {
    id: "rollback",
    group: "데이터베이스",
    title: "롤백으로 취소",
    blurb: "중간에 실패하면 묶음 전체를 실행 전으로 되돌립니다.",
    tag: "실패",
    tone: "danger",
    steps: [
      {
        name: "고객",
        sub: "주문 버튼",
        layer: "web",
        shape: "sphere",
        title: "다시 같은 주문",
        body: "재고 10에서 시작합니다. 재고 차감까지는 커밋 시나리오와 같고, 그 다음 결제가 거절됩니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "대기",
        acid: [],
        tone: "work",
      },
      {
        name: "BEGIN",
        sub: "작업 묶음 시작",
        layer: "db",
        shape: "torus",
        title: "먼저 트랜잭션을 연다",
        body: "실패할 수도 있는 결제와 재고 차감을 같은 묶음에 넣으려고 BEGIN을 먼저 실행합니다.",
        code: "BEGIN;",
        ...stockOk,
        tx: "진행 중",
        connection: "트랜잭션에 고정",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "임시 반영",
        layer: "db",
        shape: "cylinder",
        title: "재고를 임시로 9로 본다",
        body: "UPDATE는 실행됐습니다. 이 트랜잭션 안에서는 재고가 9이지만, 확정값은 10입니다. 아직 다른 손님의 재고는 10입니다.",
        code: "UPDATE books\nSET stock = stock - 1\nWHERE id = 42\n  AND stock >= 1;",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 연결 유지",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "결제 거절",
        sub: "예외 발생",
        layer: "app",
        shape: "octa",
        title: "결제가 거절된다",
        body: "주문 INSERT 전에 결제 승인이 실패했습니다. 여기서 멈추고 COMMIT하면 재고만 줄어든 채 확정됩니다. 그래서 애플리케이션은 커밋 대신 롤백을 선택합니다.",
        code: "결제 승인 실패\n-- COMMIT 하지 않음",
        ...stockTemp,
        tx: "진행 중",
        connection: "아직 묶음 안",
        acid: ["A"],
        tone: "danger",
      },
      {
        name: "ROLLBACK",
        sub: "전부 취소",
        layer: "db",
        shape: "octa",
        title: "롤백하면 재고 10으로 돌아온다",
        body: "ROLLBACK은 BEGIN 이후의 변경을 버립니다. UPDATE가 실행됐다는 사실은 확정 데이터에 남지 않습니다. 재고 10, 주문 0. 실패한 주문은 창고를 바꾸지 못했습니다.",
        code: "ROLLBACK;",
        ...stockOk,
        tx: "롤백됨",
        connection: "풀로 반환 가능",
        acid: ["A", "C"],
        tone: "danger",
        echoBack: true,
        callout: "손님에게는 실패를 알립니다. 데이터는 주문 요청 전과 같습니다. 트랜잭션 없이 시나리오에서는 이 자리에서 재고가 9로 남았습니다.",
      },
    ],
  },
  {
    id: "spring-ok",
    group: "스프링 실무",
    title: "주문 성공과 커밋",
    blurb: "@Transactional 메서드가 끝나면 스프링이 커밋합니다.",
    tag: "실무",
    tone: "ok",
    steps: [
      {
        name: "브라우저",
        sub: "POST /orders",
        layer: "web",
        shape: "sphere",
        title: "브라우저가 주문을 보낸다",
        body: "화면의 주문 버튼이 HTTP 요청을 보냅니다. 스프링을 아직 배우지 않았어도, 요청이 컨트롤러에 도착한 뒤 서비스 메서드 하나를 경계로 트랜잭션이 열린다고 보면 됩니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "컨트롤러",
        sub: "OrderController",
        layer: "web",
        shape: "box",
        title: "컨트롤러는 서비스를 호출만 한다",
        body: "컨트롤러는 HTTP를 받고 응답을 돌려주는 역할에 머뭅니다. 재고와 주문을 묶는 경계는 서비스 메서드에 둡니다. 컨트롤러 메서드마다 트랜잭션을 걸면 범위가 불필요하게 넓어지기 쉽습니다.",
        code: "@PostMapping(\"/orders\")\npublic Order place(@RequestBody OrderRequest req) {\n  return orderService.placeOrder(req.bookId(), req.qty());\n}",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "프록시",
        sub: "호출을 가로챔",
        layer: "spring",
        shape: "octa",
        title: "스프링 프록시가 먼저 받는다",
        body: "OrderService에 @Transactional이 있으면 스프링은 그 빈을 프록시로 감쌉니다. 컨트롤러가 주입받는 것은 실제 객체가 아니라 이 프록시입니다. placeOrder 호출은 프록시가 먼저 받고, 트랜잭션을 연 다음 실제 메서드를 실행합니다.",
        code: "@Configuration\n@EnableTransactionManagement\nclass AppConfig {\n  @Bean\n  PlatformTransactionManager txManager(DataSource ds) {\n    return new DataSourceTransactionManager(ds);\n  }\n}",
        ...stockOk,
        tx: "시작 직전",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
        callout: "같은 클래스 안에서 this.placeOrder()로 부르면 프록시를 거치지 않아 애너테이션이 동작하지 않습니다. 트랜잭션이 필요한 메서드는 바깥 빈이 public 메서드로 호출하게 둡니다. 스프링 부트에서 JPA를 쓰면 트랜잭션 매니저 빈은 대개 자동으로 등록됩니다.",
      },
      {
        name: "트랜잭션 시작",
        sub: "getTransaction",
        layer: "spring",
        shape: "torus",
        title: "매니저가 커넥션을 빌려 BEGIN 한다",
        body: "프록시 안의 TransactionInterceptor가 PlatformTransactionManager.getTransaction()을 호출합니다. DataSourceTransactionManager는 커넥션 풀에서 연결을 하나 빌리고, 자동 커밋을 끈 뒤 트랜잭션을 시작합니다. 로그에는 Acquired Connection, Creating new transaction 같은 문장이 남습니다.",
        code: "// PlatformTransactionManager\nTransactionStatus getTransaction(\n    TransactionDefinition definition);\n\n// 기본 전파 속성 REQUIRED\n// 이미 열린 트랜잭션이 있으면 거기에 참여",
        ...stockOk,
        tx: "진행 중",
        connection: "풀에서 빌려 사용 중",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "서비스 본문",
        sub: "placeOrder",
        layer: "app",
        shape: "box",
        title: "실제 메서드가 재고와 주문을 처리한다",
        body: "이제야 OrderService.placeOrder 본문이 실행됩니다. 리포지토리의 UPDATE와 INSERT는 방금 빌린 그 커넥션으로 나갑니다. 둘 다 실행됐지만 커밋 전이라 확정 재고는 10, 이 트랜잭션이 보는 재고는 9, 주문은 임시 1건입니다.",
        code: "@Service\npublic class OrderService {\n  @Transactional\n  public Order placeOrder(Long bookId, int qty) {\n    bookRepository.decreaseStock(bookId, qty);\n    return orderRepository.save(new Order(bookId, qty));\n  }\n}",
        ...orderTemp,
        tx: "진행 중",
        connection: "같은 커넥션으로 SQL",
        acid: ["A"],
        tone: "work",
      },
      {
        name: "커밋",
        sub: "commit()",
        layer: "spring",
        shape: "cone",
        title: "메서드가 정상 종료되면 커밋한다",
        body: "placeOrder가 예외 없이 반환되면 인터셉터가 manager.commit()을 호출합니다. 임시였던 재고 9와 주문 1건이 확정됩니다. 개발자가 BEGIN과 COMMIT을 직접 쓰지 않아도, 메서드 경계가 그 역할입니다.",
        code: "void commit(TransactionStatus status);\n\n// 메서드가 정상 반환되면\n// DataSourceTransactionManager가 COMMIT",
        ...orderDone,
        tx: "커밋됨",
        connection: "커밋 직후",
        acid: ["A", "D"],
        tone: "ok",
      },
      {
        name: "커넥션 반환",
        sub: "풀로 복귀",
        layer: "db",
        shape: "cylinder",
        title: "연결을 풀에 돌려주고 200을 응답한다",
        body: "트랜잭션이 끝나면 스프링은 커넥션을 DataSource 풀에 반환합니다. 연결을 요청 하나마다 새로 만들지 않고 돌려 쓰는 이유입니다. 컨트롤러는 저장된 주문을 HTTP 200으로 브라우저에 돌려줍니다.",
        code: "// DataSourceUtils\n// Returning JDBC Connection to DataSource\n\nHTTP 200\n{ \"orderId\": 1001, \"bookId\": 42, \"qty\": 1 }",
        ...orderDone,
        tx: "커밋됨",
        connection: "풀에 반환",
        acid: ["D"],
        tone: "ok",
      },
    ],
  },
  {
    id: "spring-fail",
    group: "스프링 실무",
    title: "예외가 나면 롤백",
    blurb: "RuntimeException이 나오면 기본 규칙으로 롤백합니다.",
    tag: "롤백",
    tone: "danger",
    steps: [
      {
        name: "브라우저",
        sub: "POST /orders",
        layer: "web",
        shape: "sphere",
        title: "다시 주문 요청",
        body: "요청 형태는 성공 시나리오와 같습니다. 차이는 서비스 안에서 결제 클라이언트가 예외를 던진다는 점뿐입니다.",
        code: "POST /orders\n{ \"bookId\": 42, \"qty\": 1 }",
        ...stockOk,
        tx: "없음",
        connection: "풀에서 대기",
        acid: [],
        tone: "work",
      },
      {
        name: "프록시",
        sub: "트랜잭션 경계",
        layer: "spring",
        shape: "octa",
        title: "프록시가 트랜잭션을 연다",
        body: "호출은 다시 프록시 → TransactionInterceptor → getTransaction() 순서로 들어옵니다. 커넥션을 빌리고, 서비스 본문이 돌기 전에 트랜잭션이 열려 있습니다.",
        code: "@Transactional\npublic Order placeOrder(Long bookId, int qty) {",
        ...stockOk,
        tx: "진행 중",
        connection: "풀에서 빌려 사용 중",
        acid: ["I"],
        tone: "work",
      },
      {
        name: "재고 차감",
        sub: "커밋 전 SQL",
        layer: "db",
        shape: "cylinder",
        title: "재고 UPDATE가 먼저 실행된다",
        body: "decreaseStock은 이미 데이터베이스에 전달됐습니다. 이 트랜잭션은 재고 9를 보지만 확정 재고는 10입니다. 예외가 나기 전에도 ‘이미 UPDATE 했으니 끝’이 아닙니다.",
        code: "bookRepository.decreaseStock(bookId, qty);\n// UPDATE는 실행됨, COMMIT 전",
        ...stockTemp,
        tx: "진행 중",
        connection: "같은 커넥션",
        acid: ["A", "I"],
        tone: "work",
      },
      {
        name: "런타임 예외",
        sub: "결제 실패",
        layer: "app",
        shape: "octa",
        title: "결제가 RuntimeException을 던진다",
        body: "결제 클라이언트가 승인 거절을 IllegalStateException으로 알립니다. 이 예외는 RuntimeException입니다. 스프링의 기본 롤백 규칙은 RuntimeException과 Error입니다. 체크 예외는 기본으로는 롤백하지 않고 커밋합니다.",
        code: "paymentClient.charge(bookId, qty);\n// throw new IllegalStateException(\"승인 거절\");\n\n// 체크 예외까지 롤백하려면\n// @Transactional(rollbackFor = Exception.class)",
        ...stockTemp,
        tx: "진행 중",
        connection: "아직 반납 전",
        acid: ["A"],
        tone: "danger",
        callout: "예외를 삼키고 정상 반환하면 스프링은 실패로 보지 않고 커밋합니다. 롤백이 필요하면 런타임 예외가 메서드 밖으로 나가게 두거나, rollbackFor로 대상을 지정합니다.",
      },
      {
        name: "롤백",
        sub: "rollback()",
        layer: "spring",
        shape: "octa",
        title: "인터셉터가 롤백을 호출한다",
        body: "예외가 프록시까지 올라오면 TransactionInterceptor가 manager.rollback()을 호출합니다. 재고 UPDATE는 취소되고 확정 재고는 10, 주문은 0건입니다. 공식 동작 로그에는 Invoking rollback, Rolling back JDBC transaction이 남습니다.",
        code: "void rollback(TransactionStatus status);\n\n// RuntimeException → 롤백 후 예외를 다시 던짐",
        ...stockOk,
        tx: "롤백됨",
        connection: "롤백 직후",
        acid: ["A", "C"],
        tone: "danger",
        echoBack: true,
      },
      {
        name: "응답",
        sub: "연결 반환",
        layer: "web",
        shape: "sphere",
        title: "커넥션을 반환하고 실패를 알린다",
        body: "롤백 뒤에도 커넥션은 풀로 돌아갑니다. 예외는 사라지지 않고 컨트롤러 쪽으로 전달되어 손님은 실패 응답을 받습니다. 화면은 실패, 데이터베이스는 주문 전과 같습니다.",
        code: "// Returning JDBC Connection to DataSource\n// 예외가 $Proxy.placeOrder 밖으로 전달\n\nHTTP 500\n재고 10 · 주문 0건",
        ...stockOk,
        tx: "롤백됨",
        connection: "풀에 반환",
        acid: ["A"],
        tone: "danger",
      },
    ],
  },
  ...propagationScenarios,
];
